package com.haxerus.duelcraft.client;

import com.haxerus.duelcraft.duel.message.DuelMessage;
import com.haxerus.duelcraft.duel.message.LocInfo;
import org.junit.jupiter.api.Test;

import java.util.List;

import static com.haxerus.duelcraft.core.OcgConstants.*;
import static org.junit.jupiter.api.Assertions.*;

/**
 * The duel log's lines, generated by feeding {@link ClientDuelState} the messages edopro logs.
 * Known card names fall back to their code here; hidden cards use readable generic labels.
 */
class DuelLogTest {

    private static ClientDuelState newState() {
        return new ClientDuelState(0, "Opponent", 8000, 8000, 40, 15, 0L);
    }

    private static List<String> lines(ClientDuelState state) {
        return state.duelLog.entries().stream().map(DuelLog.Entry::text).toList();
    }

    /** Puts a face-up monster in the given zone so attack and battle lines can name it. */
    private static void summon(ClientDuelState state, int code, int player, int sequence) {
        state.applyMessage(new DuelMessage.Move(code,
                new LocInfo(player, LOCATION_DECK, 0, POS_FACEDOWN_DEFENSE),
                new LocInfo(player, LOCATION_MZONE, sequence, POS_FACEUP_ATTACK), 0));
    }

    @Test
    void attackOnAMonsterNamesBothCards() {
        var state = newState();
        summon(state, 100, 0, 0);
        summon(state, 200, 1, 0);

        state.applyMessage(new DuelMessage.Attack(
                new LocInfo(0, LOCATION_MZONE, 0, POS_FACEUP_ATTACK),
                new LocInfo(1, LOCATION_MZONE, 0, POS_FACEUP_ATTACK)));

        assertEquals(List.of("\"100\" is attacking \"200\""), lines(state));
    }

    @Test
    void attackWithNoTargetIsDirect() {
        var state = newState();
        summon(state, 100, 0, 0);

        state.applyMessage(new DuelMessage.Attack(
                new LocInfo(0, LOCATION_MZONE, 0, POS_FACEUP_ATTACK), new LocInfo(0, 0, 0, 0)));

        assertEquals(List.of("\"100\" is attacking directly"), lines(state));
    }

    @Test
    void coinAndDiceResultsAreListed() {
        var state = newState();

        state.applyMessage(new DuelMessage.TossCoin(0, List.of(1, 0)));
        state.applyMessage(new DuelMessage.TossDice(0, List.of(3, 6)));

        assertEquals(List.of("Coin landed on: [Heads][Tails]", "Die landed on: [3][6]"), lines(state));
    }

    @Test
    void chainingLogsTheCardAndItsDesc() {
        var state = newState();
        summon(state, 100, 0, 0);

        state.applyMessage(new DuelMessage.Chaining(100,
                new LocInfo(0, LOCATION_MZONE, 0, POS_FACEUP_ATTACK), 0, LOCATION_MZONE, 0, 501L, 1));
        state.applyMessage(new DuelMessage.ChainNegated(1));

        assertEquals(List.of("Chain Link 1: \"100\" activated: #501", "Chain Link 1: \"100\" was negated"), lines(state));
    }

    @Test
    void chainResolutionUsesEngineIndicesAndIgnoresMissingLinks() {
        var state = newState();
        var loc = new LocInfo(0, LOCATION_MZONE, 0, POS_FACEUP_ATTACK);
        state.applyMessage(new DuelMessage.Chaining(100, loc, 0, LOCATION_MZONE, 0, 0, 3));
        state.applyMessage(new DuelMessage.Chaining(200, loc, 0, LOCATION_MZONE, 0, 0, 7));
        state.applyMessage(new DuelMessage.Chained(7));
        state.applyMessage(new DuelMessage.ChainSolving(7));
        state.applyMessage(new DuelMessage.ChainDisabled(7));
        state.applyMessage(new DuelMessage.ChainSolved(7));
        state.applyMessage(new DuelMessage.ChainSolving(3));
        state.applyMessage(new DuelMessage.ChainSolving(9));
        state.applyMessage(new DuelMessage.ChainNegated(9));
        assertEquals(List.of("Chain Link 3: \"100\" activated", "Chain Link 7: \"200\" activated",
                "Resolving Chain Link 7: \"200\"", "Chain Link 7: \"200\" was disabled",
                "Resolving Chain Link 3: \"100\""), lines(state));
    }

    @Test
    void damageStepLogsOnlyReceivedBoundaries() {
        var state = newState();
        state.applyMessage(new DuelMessage.NewPhase(PHASE_BATTLE_START));
        state.applyMessage(new DuelMessage.DamageStepStart());
        var loc = new LocInfo(0, 0, 0, 0);
        state.applyMessage(new DuelMessage.Battle(loc, 100, 0, 0, loc, 0, 0, 0));
        state.applyMessage(new DuelMessage.DamageStepEnd());
        assertEquals(List.of("Battle", "Damage Step", "Damage Step ended"), lines(state));
        assertEquals("Battle", state.phaseName());
        assertTrue(state.duelLog.entries().stream().flatMap(e -> e.segments().stream())
                .allMatch(segment -> segment.role() == DuelLog.Role.CONTEXT));
    }

    @Test
    void localizedAttackPreservesBothNamesWithoutParsingInsertedText() {
        var state = newState();
        state.hintText = new ClientDuelState.HintText() {
            public String desc(long desc) { return "effect"; }
            public String cardName(int code) { return "Dragon \"{}\""; }
            public String systemString(int code) { return code == 1619 ? "Attaque : [{}] contre [{}] !" : null; }
        };
        summon(state, 100, 0, 0);
        summon(state, 200, 1, 0);
        state.applyMessage(new DuelMessage.Attack(new LocInfo(0, LOCATION_MZONE, 0, POS_FACEUP_ATTACK),
                new LocInfo(1, LOCATION_MZONE, 0, POS_FACEUP_ATTACK)));
        var entry = state.duelLog.entries().getFirst();
        assertEquals("Attaque : [Dragon \"{}\"] contre [Dragon \"{}\"] !", entry.text());
        assertEquals(List.of("Dragon \"{}\"", "Dragon \"{}\""), entry.segments().stream()
                .filter(segment -> segment.role() == DuelLog.Role.CARD_NAME).map(DuelLog.Segment::text).toList());
        assertEquals(100, entry.code());
    }

    @Test
    void hiddenAttackCardsKeepUnknownNamesAndNoClickTarget() {
        var state = newState();
        summon(state, 0, 0, 0);
        summon(state, 0, 1, 0);
        state.applyMessage(new DuelMessage.Attack(new LocInfo(0, LOCATION_MZONE, 0, POS_FACEUP_ATTACK),
                new LocInfo(1, LOCATION_MZONE, 0, POS_FACEDOWN_DEFENSE)));
        var entry = state.duelLog.entries().getFirst();
        assertEquals("\"Unknown card\" is attacking \"Unknown card\"", entry.text());
        assertEquals(0, entry.code());
    }

    @Test
    void sanitizedTargetsUseVisiblePositionWithoutResolvingTheirIdentity() {
        var state = newState();
        state.hintText = new ClientDuelState.HintText() {
            public String desc(long desc) { return "effect"; }
            public String cardName(int code) {
                assertNotEquals(0, code, "Hidden identities must not reach the name resolver");
                return "Known card";
            }
            public String systemString(int code) { return null; }
        };
        var setCard = new LocInfo(1, LOCATION_SZONE, 0, POS_FACEDOWN_DEFENSE);
        state.applyMessage(new DuelMessage.Move(0, new LocInfo(1, 0, 0, 0), setCard, 0));
        state.applyMessage(new DuelMessage.BecomeTarget(List.of(setCard)));
        state.applyMessage(new DuelMessage.CardSelected(List.of(setCard)));
        state.applyMessage(new DuelMessage.RandomSelected(1, List.of(setCard)));
        assertEquals(List.of("Face-down card targeted", "Face-down card selected",
                "Face-down card selected at random"), lines(state));
        assertTrue(state.duelLog.entries().stream().allMatch(entry -> entry.code() == 0
                && entry.segments().stream().allMatch(segment -> segment.role() == DuelLog.Role.PLAIN)));

        summon(state, 0, 1, 0);
        state.applyMessage(new DuelMessage.BecomeTarget(
                List.of(new LocInfo(1, LOCATION_MZONE, 0, POS_FACEUP_ATTACK))));
        assertEquals("Unknown card targeted", state.duelLog.entries().getLast().text());
        summon(state, 100, 0, 0);
        state.applyMessage(new DuelMessage.BecomeTarget(
                List.of(new LocInfo(0, LOCATION_MZONE, 0, POS_FACEUP_ATTACK))));
        var known = state.duelLog.entries().getLast();
        assertEquals("\"Known card\" targeted", known.text());
        assertEquals(100, known.code());
        assertTrue(known.segments().stream().anyMatch(segment -> segment.role() == DuelLog.Role.CARD_NAME));
    }

    @Test
    void unknownReceivedPhaseIsIdentifiedWithoutInventingTransitions() {
        var state = newState();
        state.applyMessage(new DuelMessage.NewPhase(0x4000));
        assertEquals(List.of("Phase 0x4000"), lines(state));
    }

    @Test
    void lpChangesCarryTheirReason() {
        var state = newState();

        state.applyMessage(new DuelMessage.Damage(0, 500));
        state.applyMessage(new DuelMessage.Recover(1, 300));
        state.applyMessage(new DuelMessage.PayLpCost(0, 800));
        state.applyMessage(new DuelMessage.LpUpdate(0, 7000));

        assertEquals(List.of(
                "You: -500 LP (damage)",
                "Opponent: +300 LP (recover)",
                "You: -800 LP (cost)"), lines(state));
    }

    @Test
    void summonsTargetsAndMissedTimingAreLogged() {
        var state = newState();
        summon(state, 100, 0, 0);

        state.applyMessage(new DuelMessage.Summoning(100,
                new LocInfo(0, LOCATION_MZONE, 0, POS_FACEUP_ATTACK)));
        state.applyMessage(new DuelMessage.BecomeTarget(
                List.of(new LocInfo(0, LOCATION_MZONE, 0, POS_FACEUP_ATTACK))));
        state.applyMessage(new DuelMessage.MissedEffect(
                new LocInfo(0, LOCATION_MZONE, 0, POS_FACEUP_ATTACK), 100));

        assertEquals(List.of("Summoning \"100\"", "\"100\" targeted", "\"100\" missed the timing"),
                lines(state));
    }

    @Test
    void turnPhaseAndResultAreLogged() {
        var state = newState();

        state.applyMessage(new DuelMessage.NewTurn(0));
        state.applyMessage(new DuelMessage.NewPhase(PHASE_BATTLE_START));
        state.applyMessage(new DuelMessage.Win(0, 1));

        assertEquals(List.of("Turn 1 - Your turn", "Battle", "You win"), lines(state));
    }

    /** MSG_WIN and the host's DuelEndPayload both reach applyResult; only one line comes out. */
    @Test
    void aRepeatedResultIsNotLoggedTwice() {
        var state = newState();

        state.applyMessage(new DuelMessage.Win(1, 1));
        state.applyResult(1, 1);

        assertEquals(List.of("You lose"), lines(state));
    }

    @Test
    void aLineKeepsTheCodeItNames() {
        var state = newState();
        summon(state, 100, 0, 0);

        state.applyMessage(new DuelMessage.MissedEffect(
                new LocInfo(0, LOCATION_MZONE, 0, POS_FACEUP_ATTACK), 100));

        assertEquals(100, state.duelLog.entries().getFirst().code());
    }

    @Test
    void theLogKeepsOnlyItsLastTwoHundredLines() {
        var log = new DuelLog();
        for (int i = 0; i < 250; i++) log.add(0, "line " + i);

        assertEquals(200, log.entries().size());
        assertEquals("line 50", log.entries().getFirst().text());
        assertEquals("line 249", log.entries().getLast().text());
    }
}
