package com.haxerus.duelcraft.client;

import com.haxerus.duelcraft.duel.message.DuelMessage;
import com.haxerus.duelcraft.duel.message.LocInfo;
import org.junit.jupiter.api.Test;

import java.util.List;

import static com.haxerus.duelcraft.core.OcgConstants.*;
import static org.junit.jupiter.api.Assertions.*;

/**
 * The duel log's lines, generated by feeding {@link ClientDuelState} the messages edopro logs.
 * Card names fall back to the raw code here: no card database is on the test classpath.
 */
class DuelLogTest {

    private static ClientDuelState newState() {
        return new ClientDuelState(0, "Opponent", 8000, 8000, 40, 15, 0L);
    }

    private static List<String> lines(ClientDuelState state) {
        return state.duelLog.entries().stream().map(DuelLog.Entry::text).toList();
    }

    /** Puts a face-up monster in the given zone so attack and battle lines can name it. */
    private static void summon(ClientDuelState state, int code, int player, int sequence) {
        state.applyMessage(new DuelMessage.Move(code,
                new LocInfo(player, LOCATION_DECK, 0, POS_FACEDOWN_DEFENSE),
                new LocInfo(player, LOCATION_MZONE, sequence, POS_FACEUP_ATTACK), 0));
    }

    @Test
    void attackOnAMonsterNamesBothCards() {
        var state = newState();
        summon(state, 100, 0, 0);
        summon(state, 200, 1, 0);

        state.applyMessage(new DuelMessage.Attack(
                new LocInfo(0, LOCATION_MZONE, 0, POS_FACEUP_ATTACK),
                new LocInfo(1, LOCATION_MZONE, 0, POS_FACEUP_ATTACK)));

        assertEquals(List.of("\"100\" is attacking \"200\""), lines(state));
    }

    @Test
    void attackWithNoTargetIsDirect() {
        var state = newState();
        summon(state, 100, 0, 0);

        state.applyMessage(new DuelMessage.Attack(
                new LocInfo(0, LOCATION_MZONE, 0, POS_FACEUP_ATTACK), new LocInfo(0, 0, 0, 0)));

        assertEquals(List.of("\"100\" is attacking directly"), lines(state));
    }

    @Test
    void coinAndDiceResultsAreListed() {
        var state = newState();

        state.applyMessage(new DuelMessage.TossCoin(0, List.of(1, 0)));
        state.applyMessage(new DuelMessage.TossDice(0, List.of(3, 6)));

        assertEquals(List.of("Coin landed on: [Heads][Tails]", "Die landed on: [3][6]"), lines(state));
    }

    @Test
    void chainingLogsTheCardAndItsDesc() {
        var state = newState();
        summon(state, 100, 0, 0);

        state.applyMessage(new DuelMessage.Chaining(100,
                new LocInfo(0, LOCATION_MZONE, 0, POS_FACEUP_ATTACK), 0, LOCATION_MZONE, 0, 501L, 1));
        state.applyMessage(new DuelMessage.ChainNegated(1));

        assertEquals(List.of("\"100\" activated: #501", "\"100\" was negated"), lines(state));
    }

    @Test
    void lpChangesCarryTheirReason() {
        var state = newState();

        state.applyMessage(new DuelMessage.Damage(0, 500));
        state.applyMessage(new DuelMessage.Recover(1, 300));
        state.applyMessage(new DuelMessage.PayLpCost(0, 800));
        state.applyMessage(new DuelMessage.LpUpdate(0, 7000));

        assertEquals(List.of(
                "You: -500 LP (damage)",
                "Opponent: +300 LP (recover)",
                "You: -800 LP (cost)"), lines(state));
    }

    @Test
    void summonsTargetsAndMissedTimingAreLogged() {
        var state = newState();
        summon(state, 100, 0, 0);

        state.applyMessage(new DuelMessage.Summoning(100,
                new LocInfo(0, LOCATION_MZONE, 0, POS_FACEUP_ATTACK)));
        state.applyMessage(new DuelMessage.BecomeTarget(
                List.of(new LocInfo(0, LOCATION_MZONE, 0, POS_FACEUP_ATTACK))));
        state.applyMessage(new DuelMessage.MissedEffect(
                new LocInfo(0, LOCATION_MZONE, 0, POS_FACEUP_ATTACK), 100));

        assertEquals(List.of("Summoning \"100\"", "\"100\" targeted", "\"100\" missed the timing"),
                lines(state));
    }

    @Test
    void turnPhaseAndResultAreLogged() {
        var state = newState();

        state.applyMessage(new DuelMessage.NewTurn(0));
        state.applyMessage(new DuelMessage.NewPhase(PHASE_DAMAGE_CAL));
        state.applyMessage(new DuelMessage.Win(0, 1));

        assertEquals(List.of("Turn 1 - Your turn", "Damage Calc", "You win"), lines(state));
    }

    @Test
    void aLineKeepsTheCodeItNames() {
        var state = newState();
        summon(state, 100, 0, 0);

        state.applyMessage(new DuelMessage.MissedEffect(
                new LocInfo(0, LOCATION_MZONE, 0, POS_FACEUP_ATTACK), 100));

        assertEquals(100, state.duelLog.entries().getFirst().code());
    }

    @Test
    void theLogKeepsOnlyItsLastTwoHundredLines() {
        var log = new DuelLog();
        for (int i = 0; i < 250; i++) log.add(0, "line " + i);

        assertEquals(200, log.entries().size());
        assertEquals("line 50", log.entries().getFirst().text());
        assertEquals("line 249", log.entries().getLast().text());
    }
}
